### ==========================================================================
###  $Id: Makefile.sub  |  Matthew Sheets
###  FILE: demo/Makefile.sub - make the demo programs
###  bibo - another LEGO Mindstorms OS
### --------------------------------------------------------------------------

include demo/c/Makefile.sub
include demo/c++/Makefile.sub
include demo/esterel/Makefile.sub
include demo/xs-lisp/Makefile.sub
