### ==========================================================================
###  $Id: Makefile.sub 606 2007-11-14 22:02:48Z hoenicke $
###  FILE: xs/Makefile.sub - make xs
###  bibo - another LEGO Mindstorms OS
### --------------------------------------------------------------------------

DISTFILES += $(patsubst %,xs/%, README Makefile.sub)

include xs/lisp/Makefile.sub

include xs/demo/Makefile.sub
