### ==========================================================================
###  $Id: Makefile.sub  |  Matthew Sheets
###  FILE: xs/Makefile.sub - make xs
###  bibo - another LEGO MindStorms RCX OS
### --------------------------------------------------------------------------

DISTFILES += $(patsubst %,xs/%, README Makefile.sub)

include xs/lisp/Makefile.sub
