name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install h8300-hms toolchain
      run: sudo apt-get install binutils-h8300-hms gcc-h8300-hms
    - name: configure
      run: ./configure
    - name: make
      run: make
